# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
          cd backend
          go build -v ./...
     

    - name: Test
      run: |
          cd backend
          go test -v ./...
          
    - name: Run script for deployment
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ls
            cd /home/ubuntu/devops-fullstack-app
            git pull ${{ secrets.GIT_URL }} master
            cd /home/ubuntu/devops-fullstack-app/frontend
            docker build . -t frontend:v${{github.run_number}}
            cd /home/ubuntu/devops-fullstack-app/backend
            docker build . -t backend:v${{github.run_number}}
            /bin/bash /home/ubuntu/devops.sh
